WITH players AS (
			SELECT *
			FROM dbt_practice.landing.players
)
SELECT 
			CAST(PLAYER_ID 								AS INTEGER) 	AS PLAYER_ID,
			CAST(FIRST_NAME 							AS STRING) 		AS FIRST_NAME,
			CAST(LAST_NAME 								AS STRING) 		AS LAST_NAME,
			CAST(NAME 									AS STRING) 		AS NAME,
			CAST(LAST_SEASON 							AS INTEGER) 	AS LAST_SEASON,
			CAST(CURRENT_CLUB_ID 						AS INTEGER) 	AS CURRENT_CLUB_ID,
			CAST(PLAYER_CODE 							AS STRING) 		AS PLAYER_CODE,
			CAST(COUNTRY_OF_BIRTH 						AS STRING) 		AS COUNTRY_OF_BIRTH,
			CAST(CITY_OF_BIRTH 							AS STRING) 		AS CITY_OF_BIRTH,
			CAST(COUNTRY_OF_CITIZENSHIP 				AS STRING) 		AS COUNTRY_OF_CITIZENSHIP,
			CAST(DATE_OF_BIRTH 							AS DATE) 		AS DATE_OF_BIRTH,
			CAST(SUB_POSITION 							AS STRING) 		AS SUB_POSITION,
			CAST(POSITION 								AS STRING) 		AS POSITION,
			CAST(FOOT 									AS STRING) 		AS FOOT,
			CAST(HEIGHT_IN_CM 							AS INTEGER) 	AS HEIGHT_IN_CM,
			CAST(MARKET_VALUE_IN_EUR 					AS INTEGER) 	AS MARKET_VALUE_IN_EUR,
			CAST(HIGHEST_MARKET_VALUE_IN_EUR 			AS INTEGER) 	AS HIGHEST_MARKET_VALUE_IN_EUR,
			CAST(CONTRACT_EXPIRATION_DATE 				AS DATETIME) 	AS CONTRACT_EXPIRATION_DATE,
			CAST(AGENT_NAME 							AS STRING) 		AS AGENT_NAME,
			CAST(IMAGE_URL 								AS STRING) 		AS IMAGE_URL,
			CAST(URL 									AS STRING) 		AS URL,
			CAST(CURRENT_CLUB_DOMESTIC_COMPETITION_ID 	AS STRING) 		AS CURRENT_CLUB_DOMESTIC_COMPETITION_ID,
			CAST(CURRENT_CLUB_NAME 						AS STRING) 		AS CURRENT_CLUB_NAME,
			CURRENT_DATE() 												AS LoadDate,
			CAST('Transfermarkt'						AS STRING) 		AS RecordSource,
			CAST(MD5(PLAYER_ID) 						AS CHAR(32)) 	AS PlayerHashKey,
			MD5(UPPER(CONCAT(
                    TRIM(NVL(FIRST_NAME                             , '')), '||',
                    TRIM(NVL(LAST_NAME                              , '')), '||',
                    TRIM(NVL(NAME                                   , '')), '||',
                    TRIM(NVL(LAST_SEASON                            , '')), '||',
                    TRIM(NVL(CURRENT_CLUB_ID                        , '')), '||',
                    TRIM(NVL(PLAYER_CODE                            , '')), '||',
                    TRIM(NVL(COUNTRY_OF_BIRTH                       , '')), '||',
                    TRIM(NVL(CITY_OF_BIRTH                          , '')), '||',
                    TRIM(NVL(COUNTRY_OF_CITIZENSHIP                 , '')), '||',
                    TRIM(NVL(DATE_OF_BIRTH                          , '')), '||',
                    TRIM(NVL(SUB_POSITION                           , '')), '||',
                    TRIM(NVL(POSITION                               , '')), '||',
                    TRIM(NVL(FOOT                                   , '')), '||',
                    TRIM(NVL(HEIGHT_IN_CM                           , '')), '||',
                    TRIM(NVL(MARKET_VALUE_IN_EUR                    , '')), '||',
                    TRIM(NVL(HIGHEST_MARKET_VALUE_IN_EUR            , '')), '||',
                    TRIM(NVL(CONTRACT_EXPIRATION_DATE               , '')), '||',
                    TRIM(NVL(AGENT_NAME                             , '')), '||',
                    TRIM(NVL(IMAGE_URL                              , '')), '||',
                    TRIM(NVL(URL                                    , '')), '||',
                    TRIM(NVL(CURRENT_CLUB_DOMESTIC_COMPETITION_ID   , '')), '||',
                    TRIM(NVL(CURRENT_CLUB_NAME                      , ''))
			))) AS PlayerHashDiff
FROM    	players